### ISSUE TITLE
Use default global-backup reference for k8up s3 access and secret key

### ISSUE THREAD

**Issue by TheBigLee** [projectsyn/component-vault#4]
## Context
Currently the default vault reference for the s3 access and secret keys are
```
accesskey: '?{vaultkv:${customer:name}/${cluster:name}/vault/${_instance}/backup/s3_access_key}'
secretkey: '?{vaultkv:${customer:name}/${cluster:name}/vault/${_instance}/backup/s3_secret_key}'
```
This component relies on having the k8up component installed. The s3 access and secret key are already stored in vault for k8up itself to work. Instead of duplicating those keys in vault, we should leverage the existing keys and default to those keys:
```
backup:                                                                              
  bucket:                                                                            
    accesskey: '?{vaultkv:${customer:name}/${cluster:name}/global-backup/access-key}'
    secretkey: '?{vaultkv:${customer:name}/${cluster:name}/global-backup/secret-key}'
```
